name: Checkstyle

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  checkstyle:
    name: Run checkstyle via gradle check
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: oracle
            java-version: 21
        - name: Run gradle check command
        - run: ./gradlew check
