name: Java CI with Gradle

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  ci:
    name: Java CI with Gradle
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: oracle
            java-version: 21

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3

        - name: Grant execute permission to gradlew
          run: chmod +x ./gradlew

        - name: Run checkstyle
          run: ./gradlew checkstyleMain checkstyleTest

        - name: Run unit tests
          if: ${{ success() }}
          run: ./gradlew test

        - name: Build Jar file
          if: ${{ success() }}
          run: ./gradlew bootJar